name: 'On release'

permissions:
  contents: 'read'

on:
  release:
    types:
      - 'published'

jobs:
  ReleasePublishNpmjs:
    permissions:
      contents: 'read'
    uses: './.github/workflows/release-publish-npmjs.yaml'
    secrets: 'inherit'
